export const icons = [
  { name: "Frontend - React js", icon: "devicon:react" },
  { name: "Frontend - HTML", icon: "logos:html-5" },
  { name: "Frontend - CSS", icon: "logos:css-3" },
  { name: "Frontend - JavaScript js", icon: "logos:javascript" },
  { name: "Frontend - TypeScript js", icon: "logos:typescript" },
  { name: "Frontend - Next.js", icon: "logos:nextjs-icon" },
  { name: "Frontend - Gatsby", icon: "logos:gatsby" },
  { name: "Frontend - Bootstrap", icon: "logos:bootstrap" },
  { name: "Frontend - Tailwind CSS", icon: "mdi:tailwind" },
  { name: "Frontend - Material-UI", icon: "logos:material-ui" },
  { name: "Frontend - Ant Design", icon: "logos:ant-design" },
  { name: "Backend - Node.js", icon: "logos:nodejs-icon" },
  { name: "Backend - Express js", icon: "logos:express" },
  { name: "Backend - nest js ", icon: "logos:nestjs" },
  { name: "Database - Backend - MongoDB", icon: "logos:mongodb-icon" },
  { name: "Database - Backend - Cassandra", icon: "logos:cassandra" },
  { name: "Database - Backend - Elasticsearch", icon: "logos:elasticsearch" },
  { name: "Database - Backend - Prisma", icon: "skill-icons:prisma" },
  { name: "Database - Backend - PostgreSQL", icon: "logos:postgresql" },
  { name: "Database - Backend - Redis", icon: "logos:redis" },
  {
    name: "Real-time- Backend - Frontend - Socket.IO",
    icon: "logos:socket-io",
  },
  { name: "API - GraphQL", icon: "logos:graphql" },
  { name: "Deployment - Netlify", icon: "logos:netlify" },
  { name: "Deployment - Heroku", icon: "logos:heroku" },
  { name: "Deployment - Heroku", icon: "logos:hostinger" },
  { name: "Cloud Services - Backend - Frontend - AWS", icon: "logos:aws" },
  { name: "AWS - Backend - Deployment -EC2", icon: "logos:aws-ec2" },
  { name: "AWS - Backend - S3 Storage", icon: "logos:aws-s3" },
  { name: "AWS - Backend - SQS Notification", icon: "logos:aws-sqs" },
  { name: "AWS - Backend - SNS Notification", icon: "logos:aws-sns" },
  { name: "AWS - Backend - Lambda", icon: "logos:aws-lambda" },
  { name: "AWS - Backend - API Gateway", icon: "logos:aws-api-gateway" },
  { name: "AWS - Backend - CloudFront", icon: "logos:aws-cloudfront" },
  { name: "AWS - Backend - EventBridge", icon: "logos:aws-eventbridge" },
  { name: "AWS - Backend - Cognito", icon: "logos:aws-cognito" },
];
